name: business-charter-app

services:
  frontend:
    build:
      context: /
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - SUPABASE_DATABASE_PASSWORD=${SUPABASE_DATABASE_PASSWORD}
  